### ISSUE TITLE
no stacktrace for timeouts, so re-runs everything

### ISSUE THREAD

**Issue by okram999** [NickTomlin/protractor-flake#32]
when some test fails due to timeout, there is no stacktrace. Its 'undefined'. And hence it ends up re-running all the test. Is this by design?

[chrome #1-11]
[chrome #1-11]
[chrome #1-11] Failures:
[chrome #1-11]
[chrome #1-11]   1) Open SomeTestName Test should find the Search button Function
[chrome #1-11]    Message:
[chrome #1-11]      timeout: timed out after 120000 msec waiting for spec to complete
[chrome #1-11]    Stacktrace:
[chrome #1-11]      undefined
[chrome #1-11]
[chrome #1-11] Finished in 208.122 seconds
[chrome #1-11] 4 tests, 5 assertions, 1 failure
[chrome #1-11]
# 

```
jasmineNodeOpts: {
    defaultTimeoutInterval: 120000,
    onComplete: null,
    isVerbose: true,
    showColors: true,
   includeStackTrace: true
},
```

**Comment by NickTomlin** [comment]
Hi there, 

Protractor flake is not very smart and can only selectively re-run tests if it knows which test files failed. I haven't found a great way of fixing this (since protractor requires file paths and not spec names). 

If you can think of a way to solve this please feel free to submit a pull request. Thanks!

**Comment by NickTomlin** [comment]
Going to go ahead and close this since it's a known issue that needs a fix. Again, PRs are very much welcome 😄
