### ISSUE TITLE
Running all tests in a file instead of specific one

### ISSUE THREAD

**Issue by GuyMograbi** [NickTomlin/protractor-flake#63]
It is possible in protractor to run specific tests within files

https://github.com/angular/protractor/issues/164

```
protractor --specs='tests/e2e/login.js' --grep="SingleLoginTest"
```

**Comment by wswebcreation** [comment]
Hi @GuyMograbi 

Tnx for the question and for the info. For what I understand from the thread is that is is possible, but not stable.

If we look at protractor-flake then it can only determine **which files** hold failed specs, it **can't** only run the failed tests in 1 file. So for example:

```
failing.example.spec.js
 |_ 2 failing tests
 |_ 5 passed tests

passed.example.spec.js
|_15 passed tests
```

In this case protractor-flake will read the console log and will see that `failing.example.spec.js` is failing. It will then collect the path in which the spec is stored and offers it again to Protractor. It **can't** offer only the 2 failing tests in `failing.example.specs.js` (you can't also do this manual unless you adjust the spec-file) because it (currently) **can't** determine which specific test failed.

**Comment by wswebcreation** [comment]
@GuyMograbi 

Is this clear for you or do you have any other questions? I'm going to close this issue now but it's still open for discussion
