### ISSUE TITLE
Use JUnitXML output with grep ?

### ISSUE THREAD

**Issue by ashubham** [NickTomlin/protractor-flake#69]
Hey @NickTomlin would it be better we get rid of the Regex parsing we do for the protractor output and use the JUnitXML reporter instead ? Once we find failing tests from there we could just rerun the failed tests using the `grep` option provided.

**Comment by NickTomlin** [comment]
That would require everyone to use the JUnitXML reporter, which I don't necessarily want to do.

 I'd be happy to talk about solutions that could use this though and add it as an option for a custom parser. I'd be super happy to collaborate on a PR!

**Comment by NickTomlin** [comment]
I'm still very open to a PR here but I won't have time to pursue this myself. I think the future is going to be about using structured reporting (instead of trying to regex through output) so this is definitely the right direction.

I'm going to close this but please feel free to open a PR or another issue with some thoughts on implementation! Thanks 😄
