### ISSUE TITLE
Working with angular-cli

### ISSUE THREAD

**Issue by gawicks** [NickTomlin/protractor-flake#75]
I would like to use protractor flake with ng e2e. Is this currently possible?

**Comment by wswebcreation** [comment]
Yes you can, but you need to edit the tasks in Angular-Cli to run protractor from a protractor-flake file.

See the [usage](https://github.com/NickTomlin/protractor-flake/blob/master/src/index.js) how to configure protractor-flake, but check angular-cli how to edit the `ng e2e` task to run protractor with protractor-flake.

I don't know how to edit this exactly in angular-cli so I would advice you to ask it there. I'm going to close this for now because it involves integration with other software we don't directly have knowledge of.

**Comment by NickTomlin** [comment]
@gawicks once you get things up and running feel free to add a pull request with a angular-cli section to the [docs](https://github.com/NickTomlin/protractor-flake/tree/master/docs)
