### ISSUE TITLE
how to use protractor arguments with yarn

### ISSUE THREAD

**Issue by muratkeremozcan** [NickTomlin/protractor-flake#99]
- OS: Win10
- Node.js: v10.8.0
- Protractor version: ^5.3.2
- Protractor flake version: ^3.3.0

Very cool tool and we would love to use it in our org.

Keeping it very simple and running it through CLI: there no changes in protractor.conf.js file or no new files in root (ex: protractor-retry-flake.js). 

We are using yarn and this works:  `yarn protractor-flake --max-attempts=5`
We desire to run the same against a different conf file, and cannot make it work with yarn. 

For example this does not work: 
`yarn protractor-flake --max-attempts=1 -- protractor-remote.conf.js`  

This works with plain protractor:
`protractor protractor-remote.conf.js`

Here is a list of other cli commands that did not work:
```
yarn protractor-flake --max-attempts=1 --protractor-args=['protractor-remote.conf.js']
yarn protractor-flake --max-attempts=1 -- protractor-remote.conf.js
yarn protractor-flake --max-attempts=1 ./protractor-remote.conf.js
yarn protractor-flake --max-attempts=1 -- ./protractor-remote.conf.js
yarn protractor-flake --max-attempts=1 --./protractor-remote.conf.js
yarn protractor-flake --max-attempts=1 protractor-remote.conf.js
yarn protractor-flake --max-attempts=1 --protractor-args=["protractor-remote.conf.js"]
```

Would you confirm whether yarn is supported? If not, all well. 
If yarn is supported, would you suggest a CLI command for running protractor-flake with an alternate conf file?

**Comment by NickTomlin** [comment]
Sorry for the late response. I currently do not use `yarn` or windows but I don't think there should be an issue with what you are trying to do, although it may look a little strange:


Given a `package.json` with the following `scripts` entry:

```
"scripts": {
  "flake": "protractor-flake --max-attempts=1"
}
```

You _should_ (🤞) be able to use this command:

```
yarn run protractor-flake -- -- protractor-remote.conf.js
```

Which I think will be interpreted as  `protractor-flake --max-attempts=1 -- protractor-remote.conf.js`. The double `--` is required because `yarn run` also uses `--` to signify "take these arguments and pass them to the script I am `run`ing" and `protractor-flake` takes the first non `

Here's a [gist](https://gist.github.com/NickTomlin/7cd3ca0da9fe158ea0dc997c640b3dbd) example with a simple script.

**Comment by NickTomlin** [comment]
going to close this due to inactivity. Let me know if you'd like me to reopen.
